### ISSUE TITLE
Add settings in Admin Panel for several features

### ISSUE THREAD

**Issue by colfes** [FIUS/Drinklist#62]
- Possibility to disable new header about data security (unnecessary in other use cases)
- Possibility to disable stock amount in user page
Less important:
- Option to only show X last drinks in Y last hours/days/weeks in user page history
- Features to enter a personal title for the site (name thats displayed in the tab, currently daGL/ToBL)

**Comment by mee4895** [comment]
Right now the personal title can be changed in the translation files but I consider making it a setting in the admin page
